version: '3.8'

services:

  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: agenda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
  quarkus-backend:
    build:
      context: ./back-evento
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-backend
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/agenda
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  react-app:
    build:
      context: ./front-evento-react
      dockerfile: /Dockerfile
    container_name: react-app
    ports:
       - "3000:3000"
    environment:
       REACT_APP_BACKEND_URL: http://quarkus-backend:8080
    depends_on:
     - quarkus-backend

  angular-app:
    build: ./front-evento-angular
    container_name: angular-app
    ports:
      - "4200:4200"
    environment:
      ANGULAR_APP_BACKEND_URL: http://quarkus-backend:8080
    depends_on:
     - quarkus-backend


volumes:
  cache:
    driver: local

networks:
  default:
    driver: bridge
